auth_module/urls.py
from django.urls import path
from . import views


app_name = "auth_module"

urlpatterns = [
    path('', views.redirect_to_index),
    path('sign-up', views.registration_page, name="registr_page"),
    path('sign-in', views.login_page, name="login_page"),

    path('sign-up/registr', views.registr_user, name="registr_user"),
    path('sign-in/login', views.login_user, name="login_user"),
    path('sign-out', views.logout_user, name="logout"),
    ]

catalogue_module/urls.py
from django.urls import path
from . import views


app_name = "catalogue_module"

urlpatterns = [
    path('', views.redirect_to_index, name='redirect_to_index'),
    path('categories/<int:category_id>/', views.catalogue_page, name='catalogue'),
    path('book/<int:book_id>/', views.book_page, name="book_page"),
    path('book/add_to_cart/<int:book_id>/', views.add_to_cart, name="add_to_cart"),
    path('book/<int:book_id>/add_review/', views.add_review, name="add_review"),
    path('author/', views.authors_page, name='authors_page'),
    path('author/<int:author_id>/', views.author_page, name="author_page"),
    path('discounts/', views.discounts_page, name='discounts_page'),
    path('search/', views.search, name='search'),
    path('cart/', views.cart_page, name='cart_page'),
    path('cart/remove/<int:cart_id>/<int:book_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/remove/all/', views.clear_cart, name='clear_cart'),
    path('cart/confirm/<int:cart_id>/', views.confirm_payment, name='confirm_payment'),
    path('cart/confirm/all/', views.confirm_all_payments, name='confirm_all'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_page, name="main"),
    path('profile/', views.profile_page, name="profile"),
    path('auth/', include('auth_module.urls')),
    path('catalogue/', include('catalogue_module.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/author.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <!-- todo: rename classes to avoid confusion to smth more neutral -->
        <div class="book-data">
            <div class="summary">
                <div class="book-cover">
                    <img src="{{ author.image.url }}">
                </div>
            </div>

            <div class="description">
                <h1>{{ author.name }}</h1>
                <br>
                <p>{{ author.bio }}</p>
                <br>
                {% if author.date_of_birth %}
                    <p>Дата рождения: {{ author.date_of_birth|date:"d.m.Y" }}</p>
                {% else %}
                    <p>Дата рождения: неизвестно</p>
                {% endif %}
            </div>
        </div>

        <p>Книги автора:</p>
        <div class="authors-books">
            {% for book in books %}
                {% include "parts/item-card.html" with book=book %}
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/authors-list.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <div class="authors-cards">
            {% for author in authors %}
                <div class="author-card">
                    <a href="{% url 'catalogue_module:author_page' author.id %}">
                        <div class="author-ico">
                            <img src="{{ author.image.url }}" alt="{{ author.name }}">
                        </div>
                        <p>{{ author.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/book.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <div class="book-data">
            <div class="summary">
                <div class="book-cover">
                    <img src="{{ book.cover.url }}">
                </div>

                {% if book.discount > 0 %}
                    <div class="price-tag">
                        <p class="old-price">{{ book.price }}</p>
                        <p>{{ book.total_price }}руб.</p>
                    </div>
                {% else %}
                    <div class="price-tag">
                        <p>{{ book.price }}руб.</p>
                    </div>
                {% endif %}

                <div class="stock-data">
                    {% if book.stock > 0 %}
                        <p>Осталось: {{ book.stock }}</p>
                        <a href="{% url 'catalogue_module:add_to_cart' book.id %}">
                            <div class="btn">
                                <p>В корзину</p>
                            </div>
                        </a>
                    {% else %}
                        <p>Товар закончился</p>
                    {% endif %}
                </div>
            </div>

            <div class="description">
                <h1>{{ book.title }}</h1>
                <h3>{{ book.author }}</h3>
                <br>
                <p>{{ book.description }}</p>
                <br>
                <p>Жанры: {% for entry in book.categories.all %}{{ entry.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                <p>Дата издания: {{ book.release_date|date:"d.m.Y" }}</p>
                <p>Количество страниц: {{ book.pages }}</p>
            </div>
        </div>

        <div class="reviews">
            <form action="{% url 'catalogue_module:add_review' book.id %}" method="post" autocomplete="off">
                {% csrf_token %}
                <label for="new_review">Отставить отзыв:</label>
                <textarea id="new_review" name="new_review" required placeholder="Авторизируйтесь чтобы оставить отзыв"></textarea>
                {% if user.is_authenticated %}
                    <input type="submit" value="Отправить">
                {% else %}
                    <input type="submit" value="Отправить" disabled>
                {% endif %}
            </form>

            <div class="review-block">
                {% for review in reviews %}
                    <div class="review">
                        <div class="user-data">
                            <b>{{ review.user }}</b>
                            <p> {{ review.date|date:"d.m.Y" }}</p>
                        </div>
                        <p>{{ review.review }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

templates/cart.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <div class="cart">
            {% if not items %}
                <p>Похоже, вы ещё ничего не выбрали</p>
            {% else %}
                <table>
                    <tr>
                        <td>Позиция</td>
                        <td>Товар</td>
                        <td>Цена</td>
                        <td>Удалить</td>
                        <td>Оплатить</td>
                    </tr>
                    {% for item in items %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ item.item.title }}</td>
                            <td>{{ item.item.total_price }} руб.</td>
                            <td>
                                <a href="{% url 'catalogue_module:remove_from_cart' item.id item.item.id %}">
                                    <p>Удалить</p>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'catalogue_module:confirm_payment' item.id %}">
                                    <p>Купить</p>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td>{{ items|length|add:"1" }}</td>
                        <td>Вся корзина</td>
                        <td>{{ total_price }} руб</td>
                        <td>
                            <a href="{% url 'catalogue_module:clear_cart' %}">
                                <p>Удалить всё</p>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'catalogue_module:confirm_all' %}">
                                <p>Купить всё</p>
                            </a>
                        </td>
                    </tr>
                </table>
            {% endif %}
        </div>
    </div>
</body>
</html>

templates/catalogue.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <div class="catalogue-page">
            <div class="categories">
                {% for entry in categories %}
                    <a href="{% url 'catalogue_module:catalogue' entry.id %}">
                        <div class="category">
                            {{ entry.title }}
                        </div>
                    </a>
                {% endfor %}
            </div>

            <div class="items">
                {% for item in items %}
                    {% include "parts/item-card.html" with book=item %}
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

templates/discounts.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <div class="authors-books">
            {% for book in books %}
                {% include "parts/item-card.html" with book=book %}
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content index-page">
        {% include "parts/menu.html" %}

        <div class="banner">
            <div class="btn prev" id="prev"><h1>&lt;</h1></div>
                {% for entry in banner %}
                <img src="{{ entry.image.url }}" alt="{{ entry.title }}"
                     {% if forloop.first %} style="display:block;" {% else %} style="display:none;" {% endif %} class="banner-img">
            {% endfor %}
            <div class="btn next" id="next"><h1>&gt;</h1></div>
        </div>

        {% for entry in categories %}
            <div class="category">
                <h3>{{ entry.category.title }}</h3>
                <div class="category-items">
                    {% for book in entry.books %}
                        {% include "parts/item-card.html" with book=book %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</body>
<script src="{% static 'scripts/index.js' %}"></script>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content auth-page">
        {% include "parts/menu.html" %}

        <div class="auth">
            <form action="{% url 'auth_module:login_user' %}" method="post" autocomplete="off">
                {% csrf_token %}
                <label for="user-email">Электронная почта</label>
                <input type="email" name="user-email" id="user-email" placeholder="example@mail.com" required>
    
                <label for="user-pass">Пароль</label>
                <input type="password" name="user-pass" id="user-pass" placeholder="Пароль" required>
    
                <input type="submit" value="Войти">
            </form>
        </div>

        <div class="message">
            {% if message %}
                <h2>{{ message }}</h2>
            {% endif %}
        </div>

        <div class="column-wrapper">
            <div class="auth-suggestion">
                <span>Ещё нет аккаунта?</span><a href="{% url 'auth_module:registr_page' %}"> Зарегистрироваться</a>
            </div>
            <div class="auth-suggestion">
                <span>Забыли пароль?</span><a href="#"> Восстановить пароль</a>
            </div>
        </div>
    </div>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <div class="profile">
            <div class="user-data">
                <p>Просмотр и изменение данных</p>
                <form action="#" method="post" autocomplete="off">
                    <label for="user-name">ФИО</label>
                    <input type="text" value="{{ user.name }}" id="user-name" name="user-name" required>
                    <label for="user-email">Логин (email)</label>
                    <input type="email" value="{{ user.email }}" id="user-email" name="user-email" required>
                    <label for="user-phone">Телефон (опциональный)</label>
                    <input type="tel" value="{% if not phone %} Похоже вы ещё не добавили свой телефон {% else %}{{ user.phone }}{% endif %}" id="user-phone" name="user-phone">
                    <label for="passwd">Подтвердите пароль</label>
                    <input type="password" id="passwd" name="passwd" required>
                    <input type="submit" value="Изменить">
                </form>
                <a href="{% url 'auth_module:logout' %}" class="btn">
                    <p>Выход</p>
                </a>
            </div>
            <div class="order-history">
                <p>История заказов</p>
                <table>
                    {% if not history %}
                        <p>Похоже вы ещё ничего не купили</p>
                    {% else %}
                        <tr>
                            <td>Дата</td>
                            <td>Товар</td>
                            <td>Цена</td>
                        </tr>
                        {% for entry in history %}
                            <tr>
                                <td>{{ entry.add_date|date:"d.m.Y" }}</td>
                                <td>{{ entry.item.title }}</td>
                                <td>{{ entry.item.price }} руб</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
</body>
</html>

templates/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content auth-page">
        {% include "parts/menu.html" %}

        <div class="auth">
            <form action="{% url 'auth_module:registr_user' %}" method="post" autocomplete="off">
                {% csrf_token %}
                <label for="user-name">ФИО</label>
                <input type="text" name="user-name" id="user-name" placeholder="ФИО" required>

                <label for="user-email">Электронная почта</label>
                <input type="email" name="user-email" id="user-email" placeholder="example@mail.com" required>

                <label for="user-pass">Пароль</label>
                <input type="password" name="user-pass" id="user-pass" placeholder="Пароль" minlength="8" required>

                <label for="user-pass-repeat">Повторите пароль</label>
                <input type="password" name="user-pass-repeat" id="user-pass-repeat" placeholder="Пароль" minlength="8" required>

                <input type="submit" value="Зарегистрироваться">
            </form>
        </div>

        <div class="message">
            {% if message %}
                <h2>{{ message }}</h2>
            {% endif %}
        </div>

        <div class="column-wrapper">
            <div class="auth-suggestion">
                <span>Уже есть аккаунт?</span><a href="{% url 'auth_module:login_page' %}"> Войти</a>
            </div>
        </div>
    </div>
</body>
</html>

templates/restore_password.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content auth-page">
        {% include "parts/menu.html" %}

        <div class="auth">
            <form action="{% url 'auth_module:login_user' %}" method="post" autocomplete="off">
                {% csrf_token %}
                <label for="user-email">Электронная почта</label>
                <input type="email" name="user-email" id="user-email" placeholder="example@mail.com" required>

                <input type="submit" value="Отправить">
            </form>
        </div>

        <div class="message">
            {% if message %}
                <h2>{{ message }}</h2>
            {% endif %}
        </div>
    </div>
</body>
</html>

templates/search.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>FableShelf</title>
</head>
<body>
    <div class="content">
        {% include "parts/menu.html" %}

        <h1 class="search-text">Запрос: {{ request }}</h1>
        {% if not books and not authors %}
            <div style="flex: 1">
                <p class="search-text">Похоже, по вашему запросу ничего нет</p>
            </div>
        {% elif books and not authors %}
            <p class="search-text">Книги:</p>
            <div class="authors-books">
                {% for book in books %}
                    {% include "parts/item-card.html" with book=book %}
                {% endfor %}
            </div>
        {% elif not books and authors %}
            <p class="search-text">Авторы:</p>
            <div class="authors-cards">
                {% for author in authors %}
                    <div class="author-card">
                        <a href="{% url 'catalogue_module:author_page' author.id %}">
                            <div class="author-ico">
                                <img src="{{ author.image.url }}" alt="{{ author.name }}">
                            </div>
                            <p>{{ author.name }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="search-text">Книги:</p>
            <div class="authors-books">
                {% for book in books %}
                    {% include "parts/item-card.html" with book=book %}
                {% endfor %}
            </div>
            <p class="search-text">Авторы:</p>
            <div class="authors-cards">
                {% for author in authors %}
                    <div class="author-card">
                        <a href="{% url 'catalogue_module:author_page' author.id %}">
                            <div class="author-ico">
                                <img src="{{ author.image.url }}" alt="{{ author.name }}">
                            </div>
                            <p>{{ author.name }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</body>
</html>