catalogue_module/urls.py
from django.urls import path
from . import views


app_name = "catalogue_module"

urlpatterns = [
    path('', views.redirect_to_index, name='redirect_to_index'),
    path('categories/<int:category_id>/', views.catalogue_page, name='catalogue'),
    path('book/<int:book_id>/', views.book_page, name="book_page"),
    path('book/add_to_cart/<int:book_id>/', views.add_to_cart, name="add_to_cart"),
    path('book/<int:book_id>/add_review/', views.add_review, name="add_review"),
    path('author/', views.authors_page, name='authors_page'),
    path('author/<int:author_id>/', views.author_page, name="author_page"),
    path('discounts/', views.discounts_page, name='discounts_page'),
    path('search/', views.search, name='search'),
    path('cart/', views.cart_page, name='cart_page'),
    path('cart/remove/<int:cart_id>/<int:book_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/remove/all/', views.clear_cart, name='clear_cart'),
    path('cart/confirm/<int:cart_id>/', views.confirm_payment, name='confirm_payment'),
    path('cart/confirm/all/', views.confirm_all_payments, name='confirm_all'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_page, name="main"),
    path('profile/', views.profile_page, name="profile"),
    path('auth/', include('auth_module.urls')),
    path('catalogue/', include('catalogue_module.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/parts/item-card.html
{% load static %}

<div class="book {% if book.stock <= 0 %} out-of-stock {% endif %} ">
    <img src="{{ book.cover.url }}" alt="{{ book.title }}">
    <div class="info">
        <p class="title">{{ book.title }}</p>
        <p class="author">{{ book.author }}</p>
        <p class="data">Страниц: {{ book.pages }}</p>
        <p class="data">Дата выхода: {{ book.release_date|date:"d.m.Y" }}</p>
        {% if book.discount > 0 %}
            <p class="data">
                <span class="old-price">{{ book.price }}</span> {{ book.total_price }} руб.
            </p>
        {% else %}
            <p class="data">{{ book.price }} руб.</p>
        {% endif %}
        <a href="{% url 'catalogue_module:book_page' book.id %}">
            <div class="btn">
                <p>Подробнее</p>
            </div>
        </a>
    </div>
</div>

templates/parts/menu.html
{% load static %}

<div class="menu">
    <a href="{% url 'main' %}">
        <div class="logo">
            <img src="{% static 'images/logo.png' %}">
        </div>
    </a>

    <div class="buttons">
        <a href="{% url 'catalogue_module:catalogue' 1 %}">
            <div class="btn"><p>Каталог</p></div>
        </a>
        <a href="{% url 'catalogue_module:authors_page' %}">
            <div class="btn"><p>Авторы</p></div>
        </a>
        <a href="{% url 'catalogue_module:discounts_page' %}">
            <div class="btn"><p>Скидки</p></div>
        </a>
    </div>

    <div class="search">
        <form action="{% url 'catalogue_module:search' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <input type="text" placeholder="Искать" id="search" name="search" required>
            <input type="submit" value="">
        </form>
    </div>

    <div class="buttons">
        <a href="{% url 'catalogue_module:cart_page' %}">
            <div class="btn"><p>Корзина</p></div>
        </a>
        <a href="{% url 'profile' %}">
            <div class="btn"><p>Профиль</p></div>
        </a>
    </div>
</div>